<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
    <PackageReference Include="FluentAssertions" Version="6.12.0" />
    <PackageReference Include="Testcontainers" Version="3.12.3" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.20" />
    <PackageReference Include="coverlet.collector" Version="6.0.2" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Tournament.Api\Tournament.Api.csproj" />
    <ProjectReference Include="..\..\src\Simulator.Worker\Simulator.Worker.csproj" />
    <ProjectReference Include="..\..\src\Tournament.Application\Tournament.Application.csproj" />
    <ProjectReference Include="..\..\src\Tournament.Infrastructure\Tournament.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Tournament.Domain\Tournament.Domain.csproj" />
    <ProjectReference Include="..\..\src\Contracts\Contracts.csproj" />
  </ItemGroup>
</Project>
